"""increase_greeks_column_precision

Revision ID: 1db38ebf2f8d
Revises: 8520352a70e3
Create Date: 2026-01-06 21:47:33.784557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1db38ebf2f8d'
down_revision: Union[str, None] = '8520352a70e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'delta_open',
               existing_type=sa.NUMERIC(precision=8, scale=6),
               type_=sa.Numeric(precision=12, scale=6),
               existing_nullable=True)
    op.alter_column('trades', 'gamma_open',
               existing_type=sa.NUMERIC(precision=8, scale=6),
               type_=sa.Numeric(precision=12, scale=6),
               existing_nullable=True)
    op.alter_column('trades', 'theta_open',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=True)
    op.alter_column('trades', 'vega_open',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'vega_open',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('trades', 'theta_open',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('trades', 'gamma_open',
               existing_type=sa.Numeric(precision=12, scale=6),
               type_=sa.NUMERIC(precision=8, scale=6),
               existing_nullable=True)
    op.alter_column('trades', 'delta_open',
               existing_type=sa.Numeric(precision=12, scale=6),
               type_=sa.NUMERIC(precision=8, scale=6),
               existing_nullable=True)
    # ### end Alembic commands ###
